
ckpt_path: test


data_workers: 6
data: /home/yijie/data/slam/KITTI/formated_kitti_raw_eigen
sequence_length: 3
img_height: 128
img_width: 416 

# Training
ckpt_dir: 
log_dir: 
learning_rate:
iter: 10000
cuda: False
batch_size: 4
save_ckpt_freq:
output_log_freq:
epochs: 1000
epoch_size: 100
seed: 1234
dispnet_encoder: 'VGG-16'
disparity_scale_normalize: False
momentum: 0.9
beta: 0.999
weight_decay: 0.9
epoch: 1000

alpha_recon_image: 1
lambda_rw: 1
lambda_ds: 1
lambda_fw: 1
lambda_fs: 1
lambda_gc: 1
geometric_consistency_alpha: 1
geometric_consistency_beta: 1

# Inference
result_dir:
