num_source: 2
ckpt_path: test


data_workers: 6
data: /home/yijie/data/slam/KITTI/formated_kitti_raw_eigen
sequence_length: 3
img_height: 128
img_width: 416 

# Training
ckpt_dir: 
log_dir: 
learning_rate:
iter: 10000
cuda: False
batch_size: 4
save_ckpt_freq:
output_log_freq:
epochs: 1000
epoch_size: 100
seed: 1234
dispnet_encoder: 'VGG-16'
disparity_scale_normalize: False

alpha_recon_image:
lambda_rw:
lambda_ds:
lambda_fw:
lambda_fs:
lambda_gc:
geometric_consistency_alpha:
geometric_consistency_beta:

# Inference
result_dir:
